### ISSUE TITLE
Kompilieren mit aktuellen Paketen

### ISSUE THREAD

**Issue by dt-flo** [latex4ei/Systemtheorie#8]
Nachdem https://github.com/latex4ei/Systemtheorie/pull/7 geschlossen wurde, weil die Änderungen zum Projekt hinzugefügt wurden, setze ich hier die Diskussion fort. 

Ich bin leider nicht so der LaTeX-Profi, daher kann ich mit den Fehlermeldungen auch nur begrenzt etwas anfangen. Deswegen frage ich hier. Bei mir treten jedes Mal fehler bei "subsection" oder "subsubsection" auf. Die Fehler sind hier zu sehen:

![Code_2020-07-02_15-08-24](https://user-images.githubusercontent.com/25205082/86362714-3bd8bc80-bc65-11ea-9e80-6a7a80022003.png)
![Code_2020-07-02_15-06-13](https://user-images.githubusercontent.com/25205082/86362718-3d09e980-bc65-11ea-9e7f-038196f7e063.png)
Das sind auch die einzigen beiden "Fehlertypen".
https://github.com/latex4ei/latex4ei-packages habe ich nicht explizit installiert, es scheinen ja alle benötigten Dateien im Master-branch vorhanden zu sein.

**Comment by hofbi** [comment]
Ich denke das ist ein Problem mit den `titlesec` package. Das hatte ich auch mal und konnte es beheben indem ich manel die neuest Version installiert habe

Das ist für linux, also müsstest du dir noch anschauen wie man das für miktex macht
```
wget http://mirrors.ctan.org/macros/latex/contrib/titlesec.zip \
    && unzip titlesec.zip \
    && rm -r /usr/share/texlive/texmf-dist/tex/latex/titlesec \
    && mv titlesec /usr/share/texlive/texmf-dist/tex/latex/.
```

**Comment by dt-flo** [comment]
Habe leider bereits 2.13 :/

**Comment by hofbi** [comment]
Könntest du es mal mit texlive unter windows versuchen. dann wissen wir ob es ein problem mit miktex oder windows generell ist.

Bzw. kannst du andere latex dokumente kompilieren und das klappt nur bei diesem repo nicht oder funktioniert latex generell nicht?

**Comment by dt-flo** [comment]
Ne, unter TeXLive treten die gleichen Fehler auf.
![2020-07-02_17-26-25](https://user-images.githubusercontent.com/25205082/86377910-7d269780-bc78-11ea-9856-385be3e15682.png)

Habe es jetzt bei Schaltungstechnik und bei Energietechnik getestet, auch bei diesen Dokumenten treten 100 Fehler auf, die gleichen wie bei Systemtheorie - immer, wenn es zu "Subsection" oder "subsubsection" geht.

Edit: Textdatei mit Fehlerinformationen hinzugefügt
[fehler.txt](https://github.com/latex4ei/Systemtheorie/files/4865265/fehler.txt)

**Comment by hofbi** [comment]
Kannst du mal dieses latex dummy dokument testen: http://latex4ei.de/downloads/latex.tex

Das verwendet keine latex4ei klassen sonder nur latex standard pakete. Wenn das auch nicht funktioniert scheint etwas mit deiner latex installation nicht zu funktionieren.

Alternativ könntest du das TUM sharelatex verwenden: https://wiki.tum.de/display/ShareLaTeX/

**Comment by dt-flo** [comment]
Das Dummy-Dokument kompiliert fehlerfrei. Ich probiere jetzt mal TUM ShareLatex.

Edit: Bei TUM ShareLatex klappt das Kompilieren des Originals. Warum gehts auf Windows nicht? Hä???

**Comment by hofbi** [comment]
Evtl. machen die latex4ei klassen die lokal dabei sind probleme und du musst sie installieren. Aber wenn das mit sharelatex klappt ist ja auch schon was.

**Comment by dt-flo** [comment]
Anscheinend gibt es da eine Menge Inkompatiblitäten, die schon mehrere Jahre bestehen:

https://tex.stackexchange.com/questions/302111/multiple-missing-number-treated-as-zero-and-illegal-unit-of-measure-pt-insert/302123
https://texwelt.de/fragen/16836/missing-number-treated-as-zero-fehler-bei-verwendung-von-section
https://tex.stackexchange.com/questions/239258/titlesec-and-chaptersection-missing-zero-error
https://www.matheplanet.com/matheplanet/nuke/html/viewtopic.php?topic=219122
https://www.komascript.de/titlesec

Vielleicht könnte man da ja mal eine Alternative finden.

**Comment by dt-flo** [comment]
Ich mach das hier mal zu, zukünftig nehm ich dann einfach TUM-ShareLatex.

**Comment by dt-flo** [comment]
Soeben auf Linux getestet. Ubuntu 20 LTS installiert, TeXLive [hier](https://www.tug.org/texlive/) heruntergeladen und installiert. Ich bekomme die selben Fehler wie auf Windows.

![2020-07-03_10-56-09](https://user-images.githubusercontent.com/25205082/86451932-17cfb680-bd0b-11ea-8ebb-1cc3bb490b42.png)

**Comment by dt-flo** [comment]
> 
> 
> Könntest du es mal mit texlive unter windows versuchen. dann wissen wir ob es ein problem mit miktex oder windows generell ist.
> 
> Bzw. kannst du andere latex dokumente kompilieren und das klappt nur bei diesem repo nicht oder funktioniert latex generell nicht?

Kannst du mir mal dein LaTeX-Setup, Titlesec-Version und Betriebsystem sagen?

**Comment by hofbi** [comment]
Ich verwende ziemlich genau das setup aus dem docker container: https://github.com/MaKeAppDev/docker-uselatex/blob/master/Dockerfile. Ubuntu 18.04 mit texlive aus der paketverwaltung.

Kannst du mal versuchen die sample FS direkt aus den Paketen zu bauen: https://github.com/latex4ei/latex4ei-packages/tree/master/template-files. Evtl. ist es ein Problem mit den klassen die direkt hier im repo liegen, das in der latest version schon gefixed ist.

**Comment by dt-flo** [comment]
Die Beispiel-FS kompiliert ohne Fehler, dafür aber mit sehr vielen Warnungen, dass im Quellcode verwendete Funktionen stark veraltet sind.

**Comment by hofbi** [comment]
Ich hab das gerade noch Mal überprüft. In den packages hab ich Mal was wegen dem titlesec package gefixed. Das wird dann vermutlich das Problem sein. Komisch nur dass es auf manchen Systemen läuft und auf manchen nicht.

Die Lösung sollte dann sein, die Klassen mit der latest version zu ersetzen.

**Comment by dt-flo** [comment]
Öhm, was genau muss ich wohin schieben?

**Comment by hofbi** [comment]
Du kannst die aktuellen Klassen löschen und einfach die neuste Version aus den packages dort einfügen. Einfach als ganzen ordner. https://www.github.com/latex4ei/Stochastische-Signale verwendet die aktuelle Version. Das kannst du als template verwenden. Dann musst du in der Formelsammlung auch noch einiges ersetzen. Die document class und es gibt auch neue Features wie sectionbox, tablebox etc.
